# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fed_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65\x64_grpc.proto\x12\x04main\"5\n\x0cregisterArgs\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04\x64oor\x18\x02 \x01(\t\x12\x0b\n\x03\x63id\x18\x03 \x01(\t\"5\n\x0bregisterOut\x12\x17\n\x0f\x63onnectedClient\x18\x01 \x01(\x08\x12\r\n\x05round\x18\x02 \x01(\x05\"=\n\x0flearningResults\x12\x16\n\x0elearningWeight\x18\x01 \x01(\x02\x12\x12\n\nsampleSize\x18\x02 \x01(\x05\"\x17\n\x08\x61\x63\x63uracy\x12\x0b\n\x03\x61\x63\x63\x18\x01 \x01(\x02\"#\n\x11\x61ggregationWeight\x12\x0e\n\x06weight\x18\x01 \x01(\x02\"\x06\n\x04void2\xbb\x01\n\x10\x46\x65\x64\x65ratedService\x12\x37\n\x0e\x63lientRegister\x12\x12.main.registerArgs\x1a\x11.main.registerOut\x12\x32\n\rstartLearning\x12\n.main.void\x1a\x15.main.learningResults\x12:\n\x0fmodelValidation\x12\x17.main.aggregationWeight\x1a\x0e.main.accuracyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fed_grpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERARGS._serialized_start=24
  _REGISTERARGS._serialized_end=77
  _REGISTEROUT._serialized_start=79
  _REGISTEROUT._serialized_end=132
  _LEARNINGRESULTS._serialized_start=134
  _LEARNINGRESULTS._serialized_end=195
  _ACCURACY._serialized_start=197
  _ACCURACY._serialized_end=220
  _AGGREGATIONWEIGHT._serialized_start=222
  _AGGREGATIONWEIGHT._serialized_end=257
  _VOID._serialized_start=259
  _VOID._serialized_end=265
  _FEDERATEDSERVICE._serialized_start=268
  _FEDERATEDSERVICE._serialized_end=455
# @@protoc_insertion_point(module_scope)
